# Generated by Django 3.2.18 on 2023-07-22 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_delete_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
    ]
